# Welcome to Jekyll!

# Website settings
title: "YZH.home"
description: "yzh's blog,use Jekyll and github pages."
keywords: "yzh,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "https://yzhihao.github.io/"
url: "https://yzhihao.github.io/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Evan'
  first_name: 'Zhihao/Evan'
  last_name: 'Ye'
  email: '1079345916@qq.com'
  github_username: 'yzhihao'
  head_img: 'static/img/landing/yzh.jpg'
  mylove: 'static/mylove/index.html'
  desc: 'i am a student come from GDUT'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-Kingdom.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'https://yzhihao.github.io/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  appid: cysfY7ULn
  conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 071a17bdc10e87d669ad01b11eb29636

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#
paginate: 5
paginate_path: "blog/page/:num"
gems: [jekyll-paginate]